//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notamedia.Oilring.Community.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notamedia.Oilring.Community.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление в список избранных на Закон.ру.
        /// </summary>
        internal static string AddToFavorMessageTitle {
            get {
                return ResourceManager.GetString("AddToFavorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос на повышение статуса Закон.ру.
        /// </summary>
        internal static string ApproveMessageTitle {
            get {
                return ResourceManager.GetString("ApproveMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение статуса на портале Закон.ру.
        /// </summary>
        internal static string ApproveStatusTitle {
            get {
                return ResourceManager.GetString("ApproveStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жалоба пользователя.
        /// </summary>
        internal static string ComplainMessageTitle {
            get {
                return ResourceManager.GetString("ComplainMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая организация на Закон.ру.
        /// </summary>
        internal static string CreateOrganizationMessageTitle {
            get {
                return ResourceManager.GetString("CreateOrganizationMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление из списка избранных на Закон.ру.
        /// </summary>
        internal static string DelFromFavorMessageTitle {
            get {
                return ResourceManager.GetString("DelFromFavorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрытие обсуждения.
        /// </summary>
        internal static string DiscussionClosed {
            get {
                return ResourceManager.GetString("DiscussionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение обратной связи.
        /// </summary>
        internal static string FeedBackMessageTitle {
            get {
                return ResourceManager.GetString("FeedBackMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приглашение на портал Закон.ру!.
        /// </summary>
        internal static string InvitationMessageTitle {
            get {
                return ResourceManager.GetString("InvitationMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый комментарий.
        /// </summary>
        internal static string NewComment {
            get {
                return ResourceManager.GetString("NewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое личное сообщение на портале Закон.ру.
        /// </summary>
        internal static string NewPrivateMessageTitle {
            get {
                return ResourceManager.GetString("NewPrivateMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановление пароля на портале Закон.ру.
        /// </summary>
        internal static string RegainPasswordMessageTitle {
            get {
                return ResourceManager.GetString("RegainPasswordMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение регистрации.
        /// </summary>
        internal static string RegistrationConfirmationMessageTitle {
            get {
                return ResourceManager.GetString("RegistrationConfirmationMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вас приветствует первая социальная сеть для юристов Закон.ру..
        /// </summary>
        internal static string RegistrationFrendsEmailsTitle {
            get {
                return ResourceManager.GetString("RegistrationFrendsEmailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос на регистрацию Закон.ру.
        /// </summary>
        internal static string RequestMessageTitle {
            get {
                return ResourceManager.GetString("RequestMessageTitle", resourceCulture);
            }
        }
    }
}
