USE oilring;
TRUNCATE TABLE Rubrics;
DECLARE @depid bigint;DECLARE @pid bigint;INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('fiziko_matematiceskie_nauki', 'Физико-математические науки', 0)
SET @depid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('matematika', 'Математика', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('vesestvennij_kompleksnij_i_funkcionalnij_analiz', 'Вещественный, комплексный и функциональный анализ', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('differencialnie_uravnenia__dinamiceskie_sistemi_i_optimalXnoe_upravlenie', 'Дифференциальные уравнения, динамические системы и оптимальное управление', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('matematiceskaa_fizika', 'Математическая физика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('geometria_i_topologia', 'Геометрия и топология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teoria_veroatnostej_i_matematiceskaa_statistika', 'Теория вероятностей и математическая статистика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('matematiceskaa_logika__algebra_i_teoria_cisel', 'Математическая логика, алгебра и теория чисел', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('vicislitelnaa_matematika', 'Вычислительная математика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('diskretnaa_matematika_i_matematiceskaa_kibernetika', 'Дискретная математика и математическая кибернетика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('mehanika', 'Механика', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teoreticeskaa_mehanika', 'Теоретическая механика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('mehanika_deformiruemogo_tverdogo_tela', 'Механика деформируемого твердого тела', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('mehanika_jidkosti__gaza_i_plazmi', 'Механика жидкости, газа и плазмы', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('dinamika_procnost_masin__priborov_i_apparaturi', 'Динамика, прочность машин, приборов и аппаратуры', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('biomehanika', 'Биомеханика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('astronomia', 'Астрономия', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('astrometria_i_nebesnaa_mehanika', 'Астрометрия и небесная механика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('astrofizika_i_zvezdnaa_astronomia', 'Астрофизика и звездная астрономия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('fizika_solnca', 'Физика Солнца', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('planetnie_issledovania', 'Планетные исследования', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('fizika', 'Физика', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('pribori_i_metodi_eksperimentalnoj_fiziki', 'Приборы и методы экспериментальной физики', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teoreticeskaa_fizika', 'Теоретическая физика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('radiofizika', 'Радиофизика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('fiziceskaa_elektronika', 'Физическая электроника', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('optika', 'Оптика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('akustika', 'Акустика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('fizika_kondensirovannogo_sostoania', 'Физика конденсированного состояния', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('fizika_plazmi', 'Физика плазмы', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('fizika_nizkih_temperatur', 'Физика низких температур', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('fizika_poluprovodnikov', 'Физика полупроводников', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('fizika_magnitnih_avlenij', 'Физика магнитных явлений', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('elektrofizika_elektrofiziceskie_ustanovki', 'Электрофизика, электрофизические установки', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teplofizika_i_teoreticeskaa_teplotehnika', 'Теплофизика и теоретическая теплотехника', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('fizika_i_tehnologia_nanostruktur__atomnaa_i_molekularnaa_fizika', 'Физика и технология наноструктур, атомная и молекулярная физика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('fizika_atomnogo_adra_i_elementarnih_castic', 'Физика атомного ядра и элементарных частиц', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('himiceskaa_fizika__gorenie_i_vzriv__fizika_ekstremalnih_sostoanij_vesestva', 'Химическая физика, горение и взрыв, физика экстремальных состояний вещества', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('kristallografia_fizika_kristallov', 'Кристаллография, физика кристаллов', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('fizika_puckov_zarajennih_castic_i_uskoritelnaa_tehnika', 'Физика пучков заряженных частиц и ускорительная техника', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('lazernaa_fizika', 'Лазерная физика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('fizika_visokih_energij', 'Физика высоких энергий', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('himiceskie_nauki', 'Химические науки', 0)
SET @depid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('himiceskie_nauki', 'Химические науки', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('neorganiceskaa_himia', 'Неорганическая химия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('analiticeskaa_himia', 'Аналитическая химия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('organiceskaa_himia', 'Органическая химия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('fiziceskaa_himia', 'Физическая химия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('elektrohimia', 'Электрохимия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('visokomolekularnie_soedinenia', 'Высокомолекулярные соединения', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('himia_elementoorganiceskih_soedinenij', 'Химия элементоорганических соединений', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('himia_visokih_energij', 'Химия высоких энергий', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('bioorganiceskaa_himia', 'Биоорганическая химия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('kolloidnaa_himia', 'Коллоидная химия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('bioneorganiceskaa_himia', 'Бионеорганическая химия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('neftehimia', 'Нефтехимия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('radiohimia', 'Радиохимия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('kinetika_i_kataliz', 'Кинетика и катализ', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('medicinskaa_himia', 'Медицинская химия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('matematiceskaa_i_kvantovaa_himia', 'Математическая и квантовая химия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('himia_tverdogo_tela', 'Химия твердого тела', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('biologiceskie_nauki', 'Биологические науки', 0)
SET @depid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('fiziko_himiceskaa_biologia', 'Физико-химическая биология', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('radiobiologia', 'Радиобиология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('biofizika', 'Биофизика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('molekularnaa_biologia', 'Молекулярная биология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('biohimia', 'Биохимия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('fiziologia_i_biohimia_rastenij', 'Физиология и биохимия растений', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('biotehnologia_v_tom_cisle_bionanotehnologii', 'Биотехнология (в том числе бионанотехнологии)', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('molekularnaa_genetika', 'Молекулярная генетика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('bioinjeneria', 'Биоинженерия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('matematiceskaa_biologia__bioinformatika', 'Математическая биология, биоинформатика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('obsaa_biologia', 'Общая биология', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('botanika', 'Ботаника', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('virusologia', 'Вирусология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('mikrobiologia', 'Микробиология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('zoologia', 'Зоология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('entomologia', 'Энтомология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('ihtiologia', 'Ихтиология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('genetika', 'Генетика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('ekologia_po_otraslam', 'Экология (по отраслям)', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('biogeohimia', 'Биогеохимия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('gidrobiologia', 'Гидробиология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('parazitologia', 'Паразитология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('mikologia', 'Микология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('pocvovedenie', 'Почвоведение', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('biologiceskie_resursi', 'Биологические ресурсы', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('fiziologia', 'Физиология', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('fiziologia', 'Физиология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('antropologia', 'Антропология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('immunologia', 'Иммунология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('kletocnaa_biologia__citologia__gistologia', 'Клеточная биология, цитология, гистология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('biologia_razvitia__embriologia', 'Биология развития, эмбриология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('nejrobiologia', 'Нейробиология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehniceskie_nauki', 'Технические науки', 0)
SET @depid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('injenernaa_geometria_i_komputernaa_grafika', 'Инженерная геометрия и компьютерная графика', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('injenernaa_geometria_i_komputernaa_grafika', 'Инженерная геометрия и компьютерная графика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('masinostroenie_i_masinovedenie', 'Машиностроение и машиноведение', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('masinovedenie_sistemi_privodov_i_detali_masin', 'Машиноведение, системы приводов и детали машин', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('trenie_i_iznos_v_masinah', 'Трение и износ в машинах', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('roboti_mehatronika_i_robototehniceskie_sistemi', 'Роботы, мехатроника и робототехнические системы', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_i_oborudovanie_mehaniceskoj_i_fiziko_tehniceskoj_obrabotki', 'Технология и оборудование механической и физико-технической обработки', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_masinostroenia', 'Технология машиностроения', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologii_i_masini_obrabotki_davleniem', 'Технологии и машины обработки давлением', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('svarka_rodstvennie_processi_i_tehnologii', 'Сварка, родственные процессы и технологии', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('metodi_kontrola_i_diagnostika_v_masinostroenii', 'Методы контроля и диагностика в машиностроении', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('masini_agregati_i_processi__po_otraslam', 'Машины, агрегаты и процессы (по отраслям)', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teoria_mehanizmov_i_masin', 'Теория механизмов и машин', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('organizacia_proizvodstva__po_otraslam', 'Организация производства (по отраслям)', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('standartizacia_i_upravlenie_kacestvom_produkcii', 'Стандартизация и управление качеством продукции', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('energeticeskoe_metallurgiceskoe_i_himiceskoe_masinostroenie', 'Энергетическое, металлургическое и химическое машиностроение', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teplovie_dvigateli', 'Тепловые двигатели', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('masini_i_apparati__processi_holodilnoj_i_kriogennoj_tehniki__sistem_kondicionirovania_i_jizneobespecenia', 'Машины и аппараты, процессы холодильной и криогенной техники, систем кондиционирования и жизнеобеспечения', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('vakuumnaa_kompressornaa_tehnika_i_pnevmosistemi', 'Вакуумная, компрессорная техника и пневмосистемы', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('atomnoe_reaktorostroenie__masini__agregati_i_tehnologia_materialov_atomnoj_promislennosti', 'Атомное реакторостроение, машины, агрегаты и технология материалов атомной промышленности', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('turbomasini_i_kombinirovannie_turboustanovki', 'Турбомашины и комбинированные турбоустановки', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('gidravliceskie_masini_i_gidropnevmoagregati', 'Гидравлические машины и гидропневмоагрегаты', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('transportnoe_gornoe_i_stroitelnoe_masinostroenie', 'Транспортное, горное и строительное машиностроение', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('kolesnie_i_gusenicnie_masini', 'Колесные и гусеничные машины', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('dorojnie_stroitelnie_i_podXemno__transportnie_masini', 'Дорожные, строительные и подъемно- транспортные машины', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('gornie_masini', 'Горные машины', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('aviacionnaa_i_raketno_kosmiceskaa_tehnika', 'Авиационная и ракетно-космическая техника', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('aerodinamika_i_processi_teploobmena_letatelnih_apparatov', 'Аэродинамика и процессы теплообмена летательных аппаратов', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('proektirovanie_konstrukcia_i_proizvodstvo_letatelnih_apparatov', 'Проектирование, конструкция и производство летательных аппаратов', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('procnost_i_teplovie_rejimi_letatelXnih_apparatov', 'Прочность и тепловые режимы летательных аппаратов', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teplovie_elektroraketnie_dvigateli_i_energoustanovki_letatelnih_apparatov', 'Тепловые, электроракетные двигатели и энергоустановки летательных аппаратов', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('nazemnie_kompleksi__startovoe_oborudovanie__ekspluatacia_letatelnih_apparatov', 'Наземные комплексы, стартовое оборудование, эксплуатация летательных аппаратов', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('kontrol_i_ispitanie_letatelXnih_apparatov_i_ih_sistem', 'Контроль и испытание летательных аппаратов и их систем', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('dinamika_ballistika__upravlenie_dvijeniem_letatelnih_apparatov', 'Динамика, баллистика, управление движением летательных аппаратов', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('innovacionnie_tehnologii_v_aerokosmiceskoj_deatelnosti', 'Инновационные технологии в аэрокосмической деятельности', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('korablestroenie', 'Кораблестроение', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teoria_korabla_i_stroitelnaa_mehanika', 'Теория корабля и строительная механика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('proektirovanie_i_konstrukcia_sudov', 'Проектирование и конструкция судов', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_sudostroenia__sudoremonta_i_organizacia_sudostroitelnogo_proizvodstva', 'Технология судостроения, судоремонта и организация судостроительного производства', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('sudovie_energeticeskie_ustanovki_i_ih_elementi__glavnie_i_vspomogatelnie', 'Судовые энергетические установки и их элементы (главные и вспомогательные)', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('fiziceskie_pola_korabla__okeana__atmosferi_i_ih_vzaimodejstvie', 'Физические поля корабля, океана, атмосферы и их взаимодействие', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('elektrotehnika', 'Электротехника', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('elektromehanika_i_elektriceskie_apparati', 'Электромеханика и электрические аппараты', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('elektrotehniceskie_materiali_i_izdelia', 'Электротехнические материалы и изделия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('elektrotehniceskie_kompleksi_i_sistemi', 'Электротехнические комплексы и системы', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teoreticeskaa_elektrotehnika', 'Теоретическая электротехника', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('svetotehnika', 'Светотехника', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('elektrotehnologia', 'Электротехнология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('silovaa_elektronika', 'Силовая электроника', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('priborostroenie_metrologia_i_informacionno_izmeritelnie_pribori_i_sistemi', 'Приборостроение, метрология и информационно-измерительные приборы и системы', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('pribori_i_metodi_izmerenia__po_vidam_izmerenij', 'Приборы и методы измерения (по видам измерений)', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('pribori_navigacii', 'Приборы навигации', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('akusticeskie_pribori_i_sistemi', 'Акустические приборы и системы', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('opticeskie_i_optiko_elektronnie_pribori_i_kompleksi', 'Оптические и оптико-электронные приборы и комплексы', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('radioizmeritelnie_pribori', 'Радиоизмерительные приборы', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('pribori_i_metodi_dla_izmerenia_ioniziruusih_izlucenij_i_rentgenovskie_pribori', 'Приборы и методы для измерения ионизирующих излучений и рентгеновские приборы', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('pribori_i_metodi_kontrola_prirodnoj_sredi__vesestv__materialov_i_izdelij', 'Приборы и методы контроля природной среды, веществ, материалов и изделий', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_priborostroenia', 'Технология приборостроения', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('metrologia_i_metrologiceskoe_obespecenie', 'Метрология и метрологическое обеспечение', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('informacionno_izmeritelnie_i_upravlausie_sistemi__po_otraslam', 'Информационно-измерительные и управляющие системы (по отраслям)', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('pribori_sistemi_i_izdelia_medicinskogo_naznacenia', 'Приборы, системы и изделия медицинского назначения', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('pribori_i_metodi_preobrazovania_izobrajenij_i_zvuka', 'Приборы и методы преобразования изображений и звука', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('radiotehnika_i_svaz', 'Радиотехника и связь', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('radiotehnika_v_tom_cisle_sistemi_i_ustrojstva_televidenia', 'Радиотехника, в том числе системы и устройства телевидения', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('antenni_svc_ustrojstva_i_ih_tehnologii', 'Антенны, СВЧ-устройства и их технологии', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('sistemi_seti_i_ustrojstva_telekommunikacij', 'Системы, сети и устройства телекоммуникаций', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('radiolokacia_i_radionavigacia', 'Радиолокация и радионавигация', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('informatika_vicislitelnaa_tehnika_i_upravlenie', 'Информатика, вычислительная техника и управление', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('sistemnij_analiz__upravlenie_i_obrabotka_informacii__po_otraslam', 'Системный анализ, управление и обработка информации (по отраслям)', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('elementi_i_ustrojstva_vicislitelnoj_tehniki_i_sistem_upravlenia', 'Элементы и устройства вычислительной техники и систем управления', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('avtomatizacia_i_upravlenie_tehnologiceskimi_processami_i_proizvodstvami__po_otraslam', 'Автоматизация и управление технологическими процессами и производствами (по отраслям)', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('upravlenie_v_socialnih_i_ekonomiceskih_sistemah', 'Управление в социальных и экономических системах', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('matematiceskoe_i_programmnoe_obespecenie_vicislitelnih_masin__kompleksov_i_kompXuternih_setej', 'Математическое и программное обеспечение вычислительных машин, комплексов и компьютерных сетей', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('sistemi_avtomatizacii_proektirovania__po_otraslam', 'Системы автоматизации проектирования (по отраслям)', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('vicislitelnie_masini__kompleksi_i_kompXuternie_seti', 'Вычислительные машины, комплексы и компьютерные сети', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teoreticeskie_osnovi_informatiki', 'Теоретические основы информатики', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('matematiceskoe_modelirovanie__cislennie_metodi_i_kompleksi_programm', 'Математическое моделирование, численные методы и комплексы программ', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('metodi_i_sistemi_zasiti_informacii__informacionnaa_bezopasnost', 'Методы и системы защиты информации, информационная безопасность', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('kvantovie_metodi_obrabotki_informacii', 'Квантовые методы обработки информации', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('energetika', 'Энергетика', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('energeticeskie_sistemi_i_kompleksi', 'Энергетические системы и комплексы', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('elektriceskie_stancii_i_elektroenergeticeskie_sistemi', 'Электрические станции и электроэнергетические системы', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('adernie_energeticeskie_ustanovki__vklucaa_proektirovanie__ekspluataciu_i_vivod_iz_ekspluatacii', 'Ядерные энергетические установки, включая проектирование, эксплуатацию и вывод из эксплуатации', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('promislennaa_teploenergetika', 'Промышленная теплоэнергетика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('energoustanovki_na_osnove_vozobnovlaemih_vidov_energii', 'Энергоустановки на основе возобновляемых видов энергии', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnika_visokih_naprajenij', 'Техника высоких напряжений', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teplovie_elektriceskie_stancii__ih_energeticeskie_sistemi_i_agregati', 'Тепловые электрические станции, их энергетические системы и агрегаты', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('metallurgia_i_materialovedenie', 'Металлургия и материаловедение', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('metallovedenie_i_termiceskaa_obrabotka_metallov_i_splavov', 'Металловедение и термическая обработка металлов и сплавов', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('metallurgia_cernih__cvetnih_i_redkih_metallov', 'Металлургия черных, цветных и редких металлов', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('litejnoe_proizvodstvo', 'Литейное производство', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('obrabotka_metallov_davleniem', 'Обработка металлов давлением', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('poroskovaa_metallurgia_i_kompozicionnie_materiali', 'Порошковая металлургия и композиционные материалы', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('metallurgia_tehnogennih_i_vtoricnih_resursov', 'Металлургия техногенных и вторичных ресурсов', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('nanotehnologii_i_nanomateriali__po_otraslam', 'Нанотехнологии и наноматериалы (по отраслям)', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('materialovedenie_po_otraslam', 'Материаловедение (по отраслям)', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('himiceskaa_tehnologia', 'Химическая технология', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_neorganiceskih_vesestv', 'Технология неорганических веществ', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_redkih__rasseannih_i_radioaktivnih_elementov', 'Технология редких, рассеянных и радиоактивных элементов', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_elektrohimiceskih_processov_i_zasita_ot_korrozii', 'Технология электрохимических процессов и защита от коррозии', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_organiceskih_vesestv', 'Технология органических веществ', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_i_pererabotka_polimerov_i_kompozitov', 'Технология и переработка полимеров и композитов', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('himiceskaa_tehnologia_topliva_i_visokoenergeticeskih_vesestv', 'Химическая технология топлива и высокоэнергетических веществ', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('processi_i_apparati_himiceskih_tehnologij', 'Процессы и аппараты химических технологий', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_silikatnih_i_tugoplavkih_nemetalliceskih_materialov', 'Технология силикатных и тугоплавких неметаллических материалов', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('membrani_i_membrannaa_tehnologia', 'Мембраны и мембранная технология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_prodovolstvennih_produktov', 'Технология продовольственных продуктов', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_obrabotki__hranenia_i_pererabotki_zlakovih__bobovih_kultur__krupanih_produktov__plodoovosnoj_produkcii_i_vinogradarstva', 'Технология обработки, хранения и переработки злаковых, бобовых культур, крупяных продуктов, плодоовощной продукции и виноградарства', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_masnih__molocnih_i_ribnih_produktov_i_holodilnih_proizvodstv', 'Технология мясных, молочных и рыбных продуктов и холодильных производств', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_sahara_i_saharistih_produktov__caa__tabaka_i_subtropiceskih_kultur', 'Технология сахара и сахаристых продуктов, чая, табака и субтропических культур', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_jirov__efirnih_masel_i_parfumerno_kosmeticeskih_produktov', 'Технология жиров, эфирных масел и парфюмерно-косметических продуктов', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('biotehnologia_pisevih_produktov_i_biologiceskih_aktivnih_vesestv', 'Биотехнология пищевых продуктов и биологических активных веществ', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('processi_i_apparati_pisevih_proizvodstv', 'Процессы и аппараты пищевых производств', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_i_tovarovedenie_pisevih_produktov_i_funkcionalnogo_i_specializirovannogo_naznacenia_i_obsestvennogo_pitania', 'Технология и товароведение пищевых продуктов и функционального и специализированного назначения и общественного питания', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('promislennoe_ribolovstvo', 'Промышленное рыболовство', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_materialov_i_izdelij_tekstilnoj_i_legkoj_promislennosti', 'Технология материалов и изделий текстильной и легкой промышленности', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('materialovedenie_proizvodstv_tekstilnoj_i_legkoj_promislennosti', 'Материаловедение производств текстильной и легкой промышленности', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_i_pervicnaa_obrabotka_tekstilnih_materialov_i_sirXa', 'Технология и первичная обработка текстильных материалов и сырья', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_svejnih_izdelij', 'Технология швейных изделий', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_koji__meha__obuvnih_i_kojevenno_galanterejnih_izdelij', 'Технология кожи, меха, обувных и кожевенно-галантерейных изделий', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('processi_i_masini_agroinjenernih_sistem', 'Процессы и машины агроинженерных систем', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologii_i_sredstva_mehanizacii_selskogo_hozajstva', 'Технологии и средства механизации сельского хозяйства', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('elektrotehnologii_i_elektrooborudovanie_v_selskom_hozajstve', 'Электротехнологии и электрооборудование в сельском хозяйстве', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologii_i_sredstva_tehniceskogo_obslujivania_v_selskom_hozajstve', 'Технологии и средства технического обслуживания в сельском хозяйстве', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_masini_i_oborudovanie_lesozagotovok__lesnogo_hozajstva__derevopererabotki_i_himiceskoj_pererabotki_biomassi_dereva', 'Технология, машины и оборудование лесозаготовок, лесного хозяйства, деревопереработки и химической переработки биомассы дерева', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_i_masini_lesozagotovok_i_lesnogo_hozajstva', 'Технология и машины лесозаготовок и лесного хозяйства', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_i_oborudovanie_himiceskoj_pererabotki_biomassi_dereva;_himia_drevesini', 'Технология и оборудование химической переработки биомассы дерева; химия древесины', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('drevesinovedenie_tehnologia_i_oborudovanie_derevopererabotki', 'Древесиноведение, технология и оборудование деревопереработки', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('transport', 'Транспорт', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('transportnie_i_transportno__tehnologiceskie_sistemi_strani__ee_regionov_i_gorodov__organizacia_proizvodstva_na_transporte', 'Транспортные и транспортно- технологические системы страны, ее регионов и городов, организация производства на транспорте', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('jeleznodorojnij_put__iziskanie_i_proektirovanie_jeleznih_dorog', 'Железнодорожный путь, изыскание и проектирование железных дорог', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('podvijnoj_sostav_jeleznih_dorog__taga_poezdov_i_elektrifikacia', 'Подвижной состав железных дорог, тяга поездов и электрификация', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('upravlenie_processami_perevozok', 'Управление процессами перевозок', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('ekspluatacia_avtomobilnogo_transporta', 'Эксплуатация автомобильного транспорта', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('navigacia_i_upravlenie_vozdusnim_dvijeniem', 'Навигация и управление воздушным движением', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('ekspluatacia_vozdusnogo_transporta', 'Эксплуатация воздушного транспорта', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('vodnie_puti_soobsenia_i_gidrografia', 'Водные пути сообщения и гидрография', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('ekspluatacia_vodnogo_transporta__sudovojdenie', 'Эксплуатация водного транспорта, судовождение', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('stroitelstvo_i_arhitektura', 'Строительство и архитектура', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('stroitelnie_konstrukcii__zdania_i_soorujenia', 'Строительные конструкции, здания и сооружения', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('osnovania_i_fundamenti__podzemnie_soorujenia', 'Основания и фундаменты, подземные сооружения', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teplosnabjenie_ventilacia__kondicionirovanie_vozduha__gazosnabjenie_i_osvesenie', 'Теплоснабжение, вентиляция, кондиционирование воздуха, газоснабжение и освещение', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('vodosnabjenie_kanalizacia__stroitelnie_sistemi_ohrani_vodnih_resursov', 'Водоснабжение, канализация, строительные системы охраны водных ресурсов', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('stroitelnie_materiali_i_izdelia', 'Строительные материалы и изделия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('gidrotehniceskoe_stroitelstvo', 'Гидротехническое строительство', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_i_organizacia_stroitelstva', 'Технология и организация строительства', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('proektirovanie_i_stroitelstvo_dorog__metropolitenov__aerodromov__mostov_i_transportnih_tonnelej', 'Проектирование и строительство дорог, метрополитенов, аэродромов, мостов и транспортных тоннелей', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('gidravlika_i_injenernaa_gidrologia', 'Гидравлика и инженерная гидрология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('stroitelnaa_mehanika', 'Строительная механика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('ekologiceskaa_bezopasnost_stroitelXstva_i_gorodskogo_hozajstva', 'Экологическая безопасность строительства и городского хозяйства', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teoria_i_istoria_arhitekturi__restavracia_i_rekonstrukcia_istoriko_arhitekturnogo_nasledia', 'Теория и история архитектуры, реставрация и реконструкция историко-архитектурного наследия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('arhitektura_zdanij_i_soorujenij._tvorceskie_koncepcii_arhitekturnoj_deatelnosti', 'Архитектура зданий и сооружений. Творческие концепции архитектурной деятельности', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('gradostroitelstvo_planirovka_selXskih_naselennih_punktov', 'Градостроительство, планировка сельских населенных пунктов', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('bezopasnost_deatelXnosti_celoveka', 'Безопасность деятельности человека', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('ohrana_truda__po_otraslam', 'Охрана труда (по отраслям)', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('bezopasnost_v_crezvicajnih_situaciah__po_otraslam', 'Безопасность в чрезвычайных ситуациях (по отраслям)', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('pojarnaa_i_promislennaa_bezopasnost__po_otraslam', 'Пожарная и промышленная безопасность (по отраслям)', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('adernaa_i_radiacionnaa_bezopasnost', 'Ядерная и радиационная безопасность', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('himiceskaa_biologiceskaa_i_bakteriologiceskaa_bezopasnost', 'Химическая, биологическая и бактериологическая безопасность', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('elektronika', 'Электроника', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tverdotelnaa_elektronika__radioelektronnie_komponenti__mikro__i_nanoelektronika__pribori_na_kvantovih_effektah', 'Твердотельная электроника, радиоэлектронные компоненты, микро- и наноэлектроника, приборы на квантовых эффектах', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('vakuumnaa_i_plazmennaa_elektronika', 'Вакуумная и плазменная электроника', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('kvantovaa_elektronika', 'Квантовая электроника', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_i_oborudovanie_dla_proizvodstva_poluprovodnikov__materialov_i_priborov_elektronnoj_tehniki', 'Технология и оборудование для производства полупроводников, материалов и приборов электронной техники', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('selskohozajstvennie_nauki', 'Сельскохозяйственные науки', 0)
SET @depid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('agronomia', 'Агрономия', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('obsee_zemledelie', 'Общее земледелие', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('melioracia_rekultivacia_i_ohrana_zemelX', 'Мелиорация, рекультивация и охрана земель', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('agrofizika', 'Агрофизика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('agrohimia', 'Агрохимия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('selekcia_i_semenovodstvo_selskohozajstvennih_rastenij', 'Селекция и семеноводство сельскохозяйственных растений', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('lugovodstvo_i_lekarstvennie__efirno__maslicnie_kulturi', 'Луговодство и лекарственные, эфирно- масличные культуры', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('zasita_rastenij', 'Защита растений', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('veterinaria_i_zootehnia', 'Ветеринария и Зоотехния', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('diagnostika_boleznej_i_terapia_jivotnih__patologia__onkologia_i_morfologia_jivotnih', 'Диагностика болезней и терапия животных, патология, онкология и морфология животных', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('veterinarnaa_mikrobiologia__virusologia__epizootologia__mikologia_s_mikotoksikologiej_i_immunologia', 'Ветеринарная микробиология, вирусология, эпизоотология, микология с микотоксикологией и иммунология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('veterinarnaa_farmakologia_s_toksikologiej', 'Ветеринарная фармакология с токсикологией', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('veterinarnaa_hirurgia', 'Ветеринарная хирургия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('veterinarnaa_sanitaria__ekologia__zoogigiena_i_veterinarno_sanitarnaa_ekspertiza', 'Ветеринарная санитария, экология, зоогигиена и ветеринарно-санитарная экспертиза', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('veterinarnoe_akuserstvo_i_biotehnika_reprodukcii_jivotnih', 'Ветеринарное акушерство и биотехника репродукции животных', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('razvedenie_selekcia_i_genetika_selskohozajstvennih_jivotnih', 'Разведение, селекция и генетика сельскохозяйственных животных', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('kormoproizvodstvo_kormlenie_selskohozajstvennih_jivotnih_i_tehnologia_kormov', 'Кормопроизводство, кормление сельскохозяйственных животных и технология кормов', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('zverovodstvo_i_ohotovedenie', 'Звероводство и охотоведение', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('castnaa_zootehnia__tehnologia_proizvodstva_produktov_jivotnovodstva', 'Частная зоотехния, технология производства продуктов животноводства', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('lesnoe_hozajstvo', 'Лесное хозяйство', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('lesnie_kulturi__selekcia__semenovodstvo', 'Лесные культуры, селекция, семеноводство', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('lesovedenie_lesovodstvo__lesoustrojstvo_i_lesnaa_taksacia', 'Лесоведение, лесоводство, лесоустройство и лесная таксация', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('agrolesomelioracia_zasitnoe_lesorazvedenie_i_ozelenenie_naselennih_punktov__lesnie_pojari_i_borba_s_nimi', 'Агролесомелиорация, защитное лесоразведение и озеленение населенных пунктов, лесные пожары и борьба с ними', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('ribnoe_hozajstvo', 'Рыбное хозяйство', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('ribnoe_hozajstvo_i_akvakultura', 'Рыбное хозяйство и аквакультура', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('gumanitarnie_nauki', 'Гуманитарные науки', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('istoriceskie_nauki_i_arheologia', 'Исторические науки и археология', 0)
SET @depid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('istoriceskie_nauki_i_arheologia', 'Исторические науки и археология', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('otecestvennaa_istoria', 'Отечественная история', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('vseobsaa_istoria__sootvetstvuusego_perioda', 'Всеобщая история (соответствующего периода)', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('arheologia', 'Археология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('etnografia_etnologia_i_antropologia', 'Этнография, этнология и антропология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('istoriografia_istocnikovedenie_i_metodi_istoriceskogo_issledovania', 'Историография, источниковедение и методы исторического исследования', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('istoria_nauki_i_tehniki', 'История науки и техники', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('istoria_mejdunarodnih_otnosenij_i_vnesnej_politiki', 'История международных отношений и внешней политики', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('filologiceskie_nauki', 'Филологические науки', 0)
SET @depid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('literaturovedenie', 'Литературоведение', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('russkaa_literatura', 'Русская литература', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('literatura_narodov_rossijskoj_federacii__s_ukazaniem_konkretnoj_literaturi_ili_gruppi_literatur', 'Литература народов Российской Федерации (с указанием конкретной литературы или группы литератур)', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('literatura_narodov_stran_zarubeja__s_ukazaniem_konkretnoj_literaturi', 'Литература народов стран зарубежья (с указанием конкретной литературы)', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teoria_literaturi._tekstologia', 'Теория литературы. Текстология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('folkloristika', 'Фольклористика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('jurnalistika', 'Журналистика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('azikoznanie', 'Языкознание', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('russkij_azik', 'Русский язык', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('aziki_narodov_rossijskoj_federacii__s_ukazaniem_konkretnogo_azika_ili_azikovoj_semi', 'Языки народов Российской Федерации (с указанием конкретного языка или языковой семьи)', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('slavanskie_aziki', 'Славянские языки', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('germanskie_aziki', 'Германские языки', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('romanskie_aziki', 'Романские языки', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('klassiceskaa_filologia__vizantijskaa_i_novogreceskaa_filologia', 'Классическая филология, византийская и новогреческая филология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teoria_azika', 'Теория языка', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('sravnitelno_istoriceskoe__tipologiceskoe_i_sopostavitelXnoe_azikoznanie', 'Сравнительно-историческое, типологическое и сопоставительное языкознание', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('prikladnaa_i_matematiceskaa_lingvistika', 'Прикладная и математическая лингвистика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('aziki_narodov_zarubejnih_stran_evropi__azii__afriki__aborigenov_ameriki_i_avstralii__s_ukazaniem_konkretnogo_azika_ili_azikovoj_semi', 'Языки народов зарубежных стран Европы, Азии, Африки, аборигенов Америки и Австралии (с указанием конкретного языка или языковой семьи)', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('filosofskie_nauki', 'Философские науки', 0)
SET @depid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('filosofskie_nauki', 'Философские науки', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('ontologia_i_teoria_poznania', 'Онтология и теория познания', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('istoria_filosofii', 'История философии', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('estetika', 'Эстетика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('etika', 'Этика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('logika', 'Логика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('filosofia_nauki_i_tehniki', 'Философия науки и техники', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('socialnaa_filosofia', 'Социальная философия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('filosofskaa_antropologia__filosofia_kulturi', 'Философская антропология, философия культуры', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('filosofia_religii_i_religiovedenie', 'Философия религии и религиоведение', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('iskusstvovedenie_i_kulturologia', 'Искусствоведение и культурология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('iskusstvovedenie', 'Искусствоведение', 0)
SET @depid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('iskusstvovedenie', 'Искусствоведение', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teatralnoe_iskusstvo', 'Театральное искусство', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('muzikalnoe_iskusstvo', 'Музыкальное искусство', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('kino_tele__i_drugie_ekrannie_iskusstva', 'Кино-, теле- и другие экранные искусства', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('izobrazitelnoe_i_dekorativno__prikladnoe_iskusstvo_i_arhitektura', 'Изобразительное и декоративно- прикладное искусство и архитектура', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('horeograficeskoe_iskusstvo', 'Хореографическое искусство', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehniceskaa_estetika_i_dizajn', 'Техническая эстетика и дизайн', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teoria_i_istoria_iskusstva', 'Теория и история искусства', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('kulturologia', 'Культурология', 0)
SET @depid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('kulturologia', 'Культурология', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teoria_i_istoria_kulturi', 'Теория и история культуры', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('muzeevedenie_konservacia_i_restavracia_istoriko_kulturnih_obXektov', 'Музееведение, консервация и реставрация историко-культурных объектов', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('dokumentalnaa_informacia', 'Документальная информация', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('dokumentalistika_dokumentovedenie__arhivovedenie', 'Документалистика, документоведение, архивоведение', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('bibliotekovedenie_bibliografovedenie_i_knigovedenie', 'Библиотековедение, библиографоведение и книговедение', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('informacionnie_sistemi_i_processi', 'Информационные системы и процессы', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('socialno_ekonomiceskie_i_obsestvennie_nauki', 'Социально-экономические и общественные науки', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('psihologiceskie_nauki', 'Психологические науки', 0)
SET @depid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('psihologiceskie_nauki', 'Психологические науки', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('obsaa_psihologia__psihologia_licnosti__istoria_psihologii', 'Общая психология, психология личности, история психологии', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('psihofiziologia', 'Психофизиология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('psihologia_truda__injenernaa_psihologia__ergonomika', 'Психология труда, инженерная психология, эргономика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('medicinskaa_psihologia', 'Медицинская психология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('socialnaa_psihologia', 'Социальная психология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('uridiceskaa_psihologia', 'Юридическая психология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('pedagogiceskaa_psihologia', 'Педагогическая психология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('korrekcionnaa_psihologia', 'Коррекционная психология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('politiceskaa_psihologia', 'Политическая психология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('psihologia_razvitia__akmeologia', 'Психология развития, акмеология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('ekonomiceskie_nauki', 'Экономические науки', 0)
SET @depid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('ekonomiceskie_nauki', 'Экономические науки', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('ekonomiceskaa_teoria', 'Экономическая теория', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('ekonomika_i_upravlenie_narodnim_hozajstvom', 'Экономика и управление народным хозяйством', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('finansi_denejnoe_obrasenie_i_kredit', 'Финансы, денежное обращение и кредит', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('buhgalterskij_ucet__statistika', 'Бухгалтерский учет, статистика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('matematiceskie_i_instrumentalnie_metodi_ekonomiki', 'Математические и инструментальные методы экономики', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('mirovaa_ekonomika', 'Мировая экономика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('pedagogiceskie_nauki', 'Педагогические науки', 0)
SET @depid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('pedagogiceskie_nauki', 'Педагогические науки', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('obsaa_pedagogika__istoria_pedagogiki_i_obrazovania', 'Общая педагогика, история педагогики и образования', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teoria_i_metodika_obucenia_i_vospitania__po_oblastam_i_urovnam_obrazovania', 'Теория и методика обучения и воспитания (по областям и уровням образования)', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('korrekcionnaa_pedagogika__surdopedagogika_i_tiflopedagogika__oligofrenopedagogika_i_logopedia', 'Коррекционная педагогика (сурдопедагогика и тифлопедагогика, олигофренопедагогика и логопедия)', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teoria_i_metodika_fiziceskogo_vospitania__sportivnoj_trenirovki__ozdorovitelnoj_i_adaptivnoj_fiziceskoj_kulXturi', 'Теория и методика физического воспитания, спортивной тренировки, оздоровительной и адаптивной физической культуры', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teoria_metodika_i_organizacia_socialno_kulXturnoj_deatelXnosti', 'Теория, методика и организация социально-культурной деятельности', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teoria_i_metodika_professionalnogo_obrazovania', 'Теория и методика профессионального образования', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('sociologiceskie_nauki', 'Социологические науки', 0)
SET @depid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('sociologiceskie_nauki', 'Социологические науки', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teoria_metodologia_i_istoria_sociologii', 'Теория, методология и история социологии', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('ekonomiceskaa_sociologia_i_demografia', 'Экономическая социология и демография', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('socialnaa_struktura__socialXnie_instituti_i_processi', 'Социальная структура, социальные институты и процессы', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('politiceskaa_sociologia', 'Политическая социология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('sociologia_kulturi', 'Социология культуры', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('sociologia_upravlenia', 'Социология управления', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('uridiceskie_nauki', 'Юридические науки', 0)
SET @depid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('uridiceskie_nauki', 'Юридические науки', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teoria_i_istoria_prava_i_gosudarstva;_istoria_ucenij_o_prave_i_gosudarstve', 'Теория и история права и государства; история учений о праве и государстве', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('konstitucionnoe_pravo;_municipalnoe_pravo', 'Конституционное право; муниципальное право', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('grajdanskoe_pravo;_predprinimatelskoe_pravo;_semejnoe_pravo;_mejdunarodnoe_castnoe_pravo', 'Гражданское право; предпринимательское право; семейное право; международное частное право', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('trudovoe_pravo;_pravo_socialnogo_obespecenia', 'Трудовое право; право социального обеспечения', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('prirodoresursnoe_pravo;_agrarnoe_pravo;_ekologiceskoe_pravo', 'Природоресурсное право; аграрное право; экологическое право', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('ugolovnoe_pravo_i_kriminologia;_ugolovno_ispolnitelnoe_pravo', 'Уголовное право и криминология; уголовно-исполнительное право', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('ugolovnij_process__kriminalistika;_operativno_rozisknaa_deatelnostX', 'Уголовный процесс, криминалистика; оперативно-розыскная деятельность', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('mejdunarodnoe_pravo;_evropejskoe_pravo', 'Международное право; Европейское право', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('sudebnaa_vlast__prokurorskij_nadzor__organizacia_pravoohranitelXnoj_deatelXnosti', 'Судебная власть, прокурорский надзор, организация правоохранительной деятельности', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('administrativnoe_pravo__finansovoe_pravo__informacionnoe_pravo', 'Административное право, финансовое право, информационное право', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('grajdanskij_process;_arbitrajnij_process', 'Гражданский процесс; арбитражный процесс', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('politologia', 'Политология', 0)
SET @depid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('politologia', 'Политология', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teoria_i_filosofia_politiki__istoria_i_metodologia_politiceskoj_nauki', 'Теория и философия политики, история и методология политической науки', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('politiceskie_instituti__processi_i_tehnologii', 'Политические институты, процессы и технологии', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('politiceskaa_kultura_i_ideologii', 'Политическая культура и идеологии', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('politiceskie_problemi_mejdunarodnih_otnosenij__globalnogo_i_regionalXnogo_razvitia', 'Политические проблемы международных отношений, глобального и регионального развития', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('politiceskaa_regionalistika._etnopolitika', 'Политическая регионалистика. Этнополитика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('konfliktologia', 'Конфликтология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('medicinskie_nauki', 'Медицинские науки', 0)
SET @depid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('kliniceskaa_medicina', 'Клиническая медицина', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('akuserstvo_i_ginekologia', 'Акушерство и гинекология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('endokrinologia', 'Эндокринология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('bolezni_uha__gorla_i_nosa', 'Болезни уха, горла и носа', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('vnutrennie_bolezni', 'Внутренние болезни', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('kardiologia', 'Кардиология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('psihiatria', 'Психиатрия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('glaznie_bolezni', 'Глазные болезни', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('pediatria', 'Педиатрия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('infekcionnie_bolezni', 'Инфекционные болезни', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('kojnie_i_venericeskie_bolezni', 'Кожные и венерические болезни', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('nervnie_bolezni', 'Нервные болезни', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('onkologia', 'Онкология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('lucevaa_diagnostika__lucevaa_terapia', 'Лучевая диагностика, лучевая терапия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('stomatologia', 'Стоматология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('travmatologia_i_ortopedia', 'Травматология и ортопедия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('ftiziatria', 'Фтизиатрия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('hirurgia', 'Хирургия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('nejrohirurgia', 'Нейрохирургия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('detskaa_hirurgia', 'Детская хирургия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('anesteziologia_i_reanimatologia', 'Анестезиология и реаниматология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('gematologia_i_perelivanie_krovi', 'Гематология и переливание крови', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('revmatologia', 'Ревматология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('urologia', 'Урология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('transplantologia_i_iskusstvennie_organi', 'Трансплантология и искусственные органы', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('pulmonologia', 'Пульмонология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('serdecno_sosudistaa_hirurgia', 'Сердечно-сосудистая хирургия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('narkologia', 'Наркология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('gastroenterologia', 'Гастроэнтерология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('nefrologia', 'Нефрология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('gerontologia_i_geriatria', 'Геронтология и гериатрия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('profilakticeskaa_medicina', 'Профилактическая медицина', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('gigiena', 'Гигиена', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('epidemiologia', 'Эпидемиология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('obsestvennoe_zdorove_i_zdravoohranenie', 'Общественное здоровье и здравоохранение', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('medicina_truda', 'Медицина труда', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('sociologia_medicini', 'Социология медицины', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('mediko_socialnaa_ekspertiza_i_mediko__socialXnaa_reabilitacia', 'Медико-социальная экспертиза и медико- социальная реабилитация', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('mediko_biologiceskie_nauki', 'Медико-биологические науки', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('anatomia_celoveka', 'Анатомия человека', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('patologiceskaa_anatomia', 'Патологическая анатомия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('patologiceskaa_fiziologia', 'Патологическая физиология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('toksikologia', 'Токсикология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('sudebnaa_medicina', 'Судебная медицина', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('farmakologia_kliniceskaa_farmakologia', 'Фармакология, клиническая фармакология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('himioterapia_i_antibiotiki', 'Химиотерапия и антибиотики', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('aviacionnaa_kosmiceskaa_i_morskaa_medicina', 'Авиационная, космическая и морская медицина', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('kliniceskaa_immunologia__allergologia', 'Клиническая иммунология, аллергология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('kliniceskaa_laboratornaa_diagnostika', 'Клиническая лабораторная диагностика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('vosstanovitelnaa_medicina__sportivnaa_medicina__lecebnaa_fizkulXtura__kurortologia_i_fizioterapia', 'Восстановительная медицина, спортивная медицина, лечебная физкультура, курортология и физиотерапия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('farmacevticeskie_nauki', 'Фармацевтические науки', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_polucenia_lekarstv', 'Технология получения лекарств', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('farmacevticeskaa_himia__farmakognozia', 'Фармацевтическая химия, фармакогнозия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('organizacia_farmacevticeskogo_dela', 'Организация фармацевтического дела', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('nauki_o_zemle', 'Науки о земле', 0)
SET @depid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('nauki_o_zemle', 'Науки о земле', @depid)
SET @pid = (SELECT @@IDENTITY);
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('obsaa_i_regionalnaa_geologia', 'Общая и региональная геология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('paleontologia_i_stratigrafia', 'Палеонтология и стратиграфия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('geotektonika_i_geodinamika', 'Геотектоника и геодинамика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('petrologia_vulkanologia', 'Петрология, вулканология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('mineralogia_kristallografia', 'Минералогия, кристаллография', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('litologia', 'Литология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('gidrogeologia', 'Гидрогеология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('injenernaa_geologia__merzlotovedenie_i_gruntovedenie', 'Инженерная геология, мерзлотоведение и грунтоведение', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('geohimia_geohimiceskie_metodi_poiskov_poleznih_iskopaemih', 'Геохимия, геохимические методы поисков полезных ископаемых', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('geofizika_geofiziceskie_metodi_poiskov_poleznih_iskopaemih', 'Геофизика, геофизические методы поисков полезных ископаемых', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('geologia_poiski_i_razvedka_tverdih_poleznih_iskopaemih__mineragenia', 'Геология, поиски и разведка твердых полезных ископаемых, минерагения', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('geologia_poiski_i_razvedka_neftanih_i_gazovih_mestorojdenij', 'Геология, поиски и разведка нефтяных и газовых месторождений', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('obogasenie_poleznih_iskopaemih', 'Обогащение полезных ископаемых', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_i_tehnika_geologorazvedocnih_rabot', 'Технология и техника геологоразведочных работ', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_burenia_i_osvoenia_skvajin', 'Технология бурения и освоения скважин', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('gornopromislennaa_i_neftegazopromislovaa_geologia__geofizika__marksejderskoe_delo_i_geometria_nedr', 'Горнопромышленная и нефтегазопромысловая геология, геофизика, маркшейдерское дело и геометрия недр', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('razrabotka_i_ekspluatacia_neftanih_i_gazovih_mestorojdenij', 'Разработка и эксплуатация нефтяных и газовых месторождений', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('tehnologia_osvoenia_morskih_mestorojdenij_poleznih_iskopaemih', 'Технология освоения морских месторождений полезных ископаемых', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('stroitelstvo_i_ekspluatacia_neftegazoprovodov__baz_i_hranilis', 'Строительство и эксплуатация нефтегазопроводов, баз и хранилищ', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('geomehanika_razrusenie_gornih_porod__rudnicnaa_aerogazodinamika_i_gornaa_teplofizika', 'Геомеханика, разрушение горных пород, рудничная аэрогазодинамика и горная теплофизика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('teoreticeskie_osnovi_proektirovania_gorno_tehniceskih_sistem', 'Теоретические основы проектирования горно-технических систем', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('geotehnologia_podzemnaa__otkritaa_i_stroitelnaa', 'Геотехнология (подземная, открытая и строительная)', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('fiziceskaa_geografia_i_biogeografia__geografia_pocv_i_geohimia_landsaftov', 'Физическая география и биогеография, география почв и геохимия ландшафтов', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('ekonomiceskaa_socialnaa__politiceskaa_i_rekreacionnaa_geografia', 'Экономическая, социальная, политическая и рекреационная география', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('geomorfologia_i_evolucionnaa_geografia', 'Геоморфология и эволюционная география', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('zemleustrojstvo_kadastr_i_monitoring_zemel', 'Землеустройство, кадастр и мониторинг земель', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('gidrologia_susi__vodnie_resursi__gidrohimia', 'Гидрология суши, водные ресурсы, гидрохимия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('okeanologia', 'Океанология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('fizika_atmosferi_i_gidrosferi', 'Физика атмосферы и гидросферы', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('meteorologia_klimatologia__agrometeorologia', 'Метеорология, климатология, агрометеорология', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('glaciologia_i_kriologia_zemli', 'Гляциология и криология Земли', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('geodezia', 'Геодезия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('kartografia', 'Картография', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('aerokosmiceskie_issledovania_zemli__fotogrammetria', 'Аэрокосмические исследования Земли, фотограмметрия', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('geoinformatika', 'Геоинформатика', @pid)
INSERT INTO Rubrics(Alias, Header, Parent_Rubric_ID) VALUES('geoekologia', 'Геоэкология', @pid)
